### ISSUE TITLE
Incremental refresh

### ISSUE THREAD

**Issue by joshkouwbb** [SafetyCulture/SafetyCulture-Power-Query-Connector#40]
Hi there,

My organisation uses SafetyCulture and I am trying to setup a report in Power BI to summarise some data. The inspection template I am interested in has 320,000+ inspections. When I use the connector it takes hours to pull this data in. I was hoping I could set up incremental refresh but in order to do so the data source query needs to support query folding. Is there any answer to whether incremental refresh can be setup with the Connector or is there any other way I can schedule refreshes without pulling all data but still seeing archived records? 

Sorry if this is not the right place to raise this, but I do not know where else to get technical support. 

Thank you,
Josh

**Comment by BCook98** [comment]
Hi @joshkouwbb,

Unfortunately incremental refreshing data using query folding is not something we support at the moment using our Power BI connector. Nor is it something on our immediate roadmap to support.

We do however offer a seperate data exporter tool that can generate CSV, SQLite DBs, or export directly to relational databases that does support incremental refreshes of data. You can read more about it here: https://developer.safetyculture.com/docs/safetyculture-exporter.

If you do need further technical support please feel free to reach out to our excellent support team at http://support.safetyculture.com.

**Comment by joshkouwbb** [comment]
Thank you, Brandon - really appreciate your quick response. I'll close the issue.
