### ISSUE TITLE
Power BI Service - how to set it up?

### ISSUE THREAD

**Issue by aikibart** [SafetyCulture/SafetyCulture-Power-Query-Connector#59]
hi all,

The Power BI template works fine on Desktop, but when publishing to the Power BI Service, I'm not able to get it to work. On one hand there are messages saying dynamic sources aren't supported, and on the other hand I think something needs to be done on the Power BI Gateway.

Does anyone know if it can be done to use the Power BI Service to refresh the report? And if so, how to do it?

Sorry if this is not the right place to raise this, but I do not know where else to get technical support.

Many thanks
Bart

**Comment by MickStanciu** [comment]
Hi @aikibart , 
we do not natively support Gateway
this is the troubleshooting document: https://help.safetyculture.com/en-US/000155/

**Comment by aikibart** [comment]
Thanks. It's a pitty it is not supported for Power BI to retrieve data directly from your api's on the Power BI Service. We will take a look at the exporter tool.
